FROM oven/bun

WORKDIR /app

ADD package.json bun.lockb .
RUN NODE_ENV=development bun i --frozen-lockfile

COPY . .

ARG VITE_MODE=production
ARG PUBLIC_COINOS_URL
ARG PUBLIC_BTC
ARG PUBLIC_DOMAIN
ARG PUBLIC_DOMAIN_TOR
ARG PUBLIC_DOMAIN_FIPS
ARG PUBLIC_DOMAIN_EXTRA
ARG PUBLIC_COINOS_NETWORK
ARG PUBLIC_COINOS_RELAY
ARG PUBLIC_COINOS_PUBKEY
ARG PUBLIC_EXPLORER
ARG PUBLIC_LIQUID_EXPLORER
ARG PUBLIC_RECAPTCHA_SITE_KEY
ARG PUBLIC_TELEGRAM_URL
ARG PUBLIC_SIMPLEX_URL
ARG PUBLIC_VAPID_PUBKEY
ARG PUBLIC_FEE_BITCOIN
ARG PUBLIC_FEE_LIGHTNING
ARG PUBLIC_FEE_LIQUID
ARG PUBLIC_FEE_USDT

RUN rm -f .env .env.local .env.production.local && \
    NODE_ENV=production bunx vite build --mode $VITE_MODE

ENV NODE_ENV=production

CMD ["bun", "./build/index.js"]
